{{ if eq .Values.elasticsearch.elastic_password "" }}
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: {{ .Release.Namespace}}
type: Opaque

data:
{{- with lookup "v1" "Secret" (.Values.elasticsearch.password.namespace | default "logging" )  .Values.elasticsearch.password.secret }}
  ## TODO: look into templatizing this value, and not hardcoding to "elastic"
  es_password: {{ .data.elastic }}
{{- end }}

{{ end }}