{{- define "check-if-there-are-tcp-ports" -}}
    {{- $allports := index . 0 -}}
    {{- range $i, $port := $allports -}}
        {{- if eq $port.protocol "TCP" -}}
            {{- nindent 1 $port.name -}}: {{ default "literally-anything" $port.protocol -}}
        {{- end -}}
    {{- end -}}
{{- end -}}

{{- define "check-if-there-are-http-ports" -}}
    {{- $allports := index . 0 -}}
    {{- range $i, $port := $allports -}}
        {{- if eq $port.protocol "HTTP" -}}
            {{- nindent 1 $port.name -}}: {{ default "literally-anything" $port.protocol -}}
        {{- end -}}
    {{- end -}}
{{- end -}}

{{- if and .Values.istio.enabled .Values.istio.fluentd.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fluentd
  namespace: {{ .Release.Namespace }}
  {{- if .Values.istio.fluentd.labels }}
  labels:
  {{ toYaml .Values.istio.fluentd.labels | indent 2 }}
  {{- end }}
  {{- if .Values.istio.fluentd.annotations }}
  annotations:
  {{ toYaml .Values.istio.fluentd.annotations | indent 2 }}
  {{- end }}

spec:
  {{- range .Values.istio.fluentd.gateways }}
  gateways:
    - {{ . }}
  {{- end }}
  {{- range .Values.istio.fluentd.hosts }}
  hosts:
    - {{ tpl . $ }}
  {{- end }}
  {{ $tcp := include "check-if-there-are-tcp-ports" (list .Values.service.ports ) }}
  {{- if gt (len $tcp) 0 -}}
  tcp:
  {{- end }}
  {{- range .Values.service.ports }}
  {{- if eq .protocol "TCP"}}
    - match:
      - port: {{ .tcpPort }}
      route:
        - destination:
            port:
              number: {{ .containerPort }}
            host: {{ include "fluentd.fullname" $ }}
  {{- end }}
  {{- end }}
  {{ $http := include "check-if-there-are-http-ports" (list .Values.service.ports ) }}
  {{- if gt (len $http) 0 -}}
  http:
  {{- end }}
  {{- range .Values.service.ports}}
  {{- if eq .protocol "HTTP" }}
    - route:
        - destination:
            port:
              number: {{ .containerPort }}
            host: {{ include "fluentd.fullname" $ }}
  {{- end }}
  {{- end }}
{{- end }}
