fluentd:
  enabled: true
  git:
    repo: https://repo1.dso.mil/big-bang/apps/sandbox/fluentd.git
    # It is recommended to update this to the latest bb tag
    tag: null
    branch: 480-epic-fluentd
    path: "chart"
  flux:
    timeout: 30m
  dependsOn:
    - name: ek
      namespace: bigbang
    - name: monitoring
      namespace: bigbang
  postRenderers:
    - kustomize:
        patches:
          # Required Patches for Prometheus ServiceMonitor scraping
          - patch: |
              - op: add
                path: /spec/endpoints/0/enableHttp2
                value: false
              - op: add
                path: /spec/endpoints/0/scheme
                value: https
              - op: add
                path: /spec/endpoints/0/tlsConfig
                value:
                  caFile: /etc/prom-certs/root-cert.pem
                  certFile: /etc/prom-certs/cert-chain.pem
                  insecureSkipVerify: true
                  keyFile: /etc/prom-certs/key.pem
            target:
              kind: ServiceMonitor
              name: fluentd
  istio:
    injection: enabled
  values:
    networkPolicies:
      enabled: true
    istio:
      enabled: true
      hardened:
        enabled: true
    elasticsearch:
      enabled: true
    upstream:
      env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: logging-ek-es-http.logging.svc.cluster.local
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_USER
          value: elastic
        - name: FLUENT_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials  # Do not change
              key: es_password                 # Do not change
      metrics:
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
      volumes:
        - name: elasticsearch-cert
          secret:
            secretName: elasticsearch-cert

      volumeMounts:
        - name: elasticsearch-cert
          mountPath: /etc/elasticsearch/certs/

      fileConfigs:
        02_filters.conf: |-
          <label @KUBERNETES>
            <match kubernetes.var.log.containers.fluentd**>
              @type relabel
              @label @FLUENT_LOG
            </match>

            <filter kubernetes.**>
              @type kubernetes_metadata
              @id filter_kube_metadata
              skip_pod_labels true
            </filter>

            <match **>
              @type relabel
              @label @DISPATCH
            </match>
          </label>

        04_outputs.conf: |-
          <label @OUTPUT>
            <match kubernetes.**>
              @type elasticsearch
              host logging-ek-es-http.logging
              port 9200
              scheme https
              user elastic
              password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
              logstash_format true
              suppress_type_name true
              include_tag_key true
              ca_file /etc/elasticsearch/certs/ca.crt
              <buffer>
                @type file
                path /var/log/fluentd-buffers/es-kube
                total_limit_size 10GB
                flush_interval 5s
              </buffer>
            </match>

            <match host.**>
              @type elasticsearch
              host logging-ek-es-http.logging
              port 9200
              scheme https
              user elastic
              password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
              logstash_format true
              suppress_type_name true
              logstash_prefix node
              ca_file /etc/elasticsearch/certs/ca.crt
              <buffer>
                @type file
                path /var/log/fluentd-buffers/es-host
                total_limit_size 10GB
                flush_interval 5s
              </buffer>
            </match>
          </label>

elasticsearchKibana:
  enabled: true

eckOperator:
  enabled: true

istioCRDs:
  enabled: true
istiod:
  enabled: true
  values:
    hardened:
      enabled: true

loki:
  enabled: false

networkPolicies:
  enabled: true

kyvernoPolicies:
  enabled: true 
  values:
    policies:
      require-non-root-group:
        exclude:
          any:
          - resources:
              namespaces:
              - fluentd
              names:
              - fluentd*
      add-default-securitycontext:
        exclude:
          any:
          - resources:
              namespaces:
              - fluentd
              names:
              - fluentd*
      require-non-root-user:
        exclude:
          any:
          - resources:
              namespaces:
              - fluentd
              names:
              - fluentd*
      restrict-host-path-mount:
        exclude:
          any:
          - resources:
              namespaces:
              - fluentd
              names:
              - fluentd* 
          - resources:
              namespaces:
              - logging
              names:
              - elasticsearch*
          - resources:
              namespaces:
              - minio-operator
              names:
              - minio*
          - resources:
              namespaces:
              - monitoring
              names:
              - monitoring*
      restrict-host-path-write:
        exclude:
          any:
          - resources:
              namespaces:
              - fluentd
              names:
              - fluentd*
          - resources:
              namespaces:
              - logging
              names:
              - elasticsearch*
          - resources:
              namespaces:
              - minio-operator
              names:
              - minio*
          - resources:
              namespaces:
              - monitoring
              names:
              - monitoring*
      restrict-volume-types:
        exclude:
          any:
          - resources:
              namespaces:
              - fluentd
              names:
              - fluentd*
          - resources:
              namespaces:
              - logging
              names:
              - elasticsearch*
          - resources:
              namespaces:
              - minio-operator
              names:
              - minio*
          - resources:
              namespaces:
              - monitoring
              names:
              - monitoring*

kyvernoReporter:
  enabled: false

promtail:
  enabled: false

alloy:
  enabled: false

kiali:
  enabled: false

neuvector:
  enabled: false

tempo:
  enabled: false

grafana:
  enabled: false

bbctl:
  enabled: false

addons:
  minioOperator:
    enabled: true